---
services: docker

env:
  # Test package install on all supported OSes.
  - distro: gallium
    playbook: test.yml
    ruby_version: 2.3.1
    ruby_path_prefix: /usr
  - distro: xenial
    playbook: test.yml
    ruby_version: 2.3.1
    ruby_path_prefix: /usr

  # Source install on latest OSes.
  - distro: xenial
    playbook: test-source.yml
    ruby_version: 2.3.0
    ruby_path_prefix: /usr/local

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false
  - export test_suite=false

  # Run tests.
  - chmod +x ${PWD}/tests/run-test.sh
  - ${PWD}/tests/run-test.sh

  # Make sure ruby is installed and at the correct version.
  - 'docker exec --tty ${container_id} env TERM=xterm which ruby'
  - 'docker exec --tty ${container_id} env TERM=xterm test -x ${ruby_path_prefix}/bin/ruby'

  - 'docker exec --tty ${container_id} env TERM=xterm ruby --version'
  - 'docker exec --tty ${container_id} env TERM=xterm ${ruby_path_prefix}/bin/ruby --version | grep -qF ${ruby_version}'

  # Make sure bundler is installed.
  - 'docker exec --tty ${container_id} env TERM=xterm ls -lah /usr/local/bin'
  - 'docker exec --tty ${container_id} env TERM=xterm which bundle'

  # Make sure user installed gems are available.
  - 'docker exec --tty ${container_id} env TERM=xterm bash --login -c "which sass"'

after_failure:
  - 'docker exec --tty ${container_id} env TERM=xterm which ruby'
  - 'docker exec --tty ${container_id} env TERM=xterm ruby --version'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/