---
# tasks file for ruby

# Install Dependencies
- name: Ensure ruby dependencies are installed
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ ruby_dependencies | list }}"

- name: Define ruby_user
  set_fact:
    ruby_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
  when: ruby_user is not defined

# Ruby Installation
- include_tasks: apt.yml
  when: ruby_install_type == 'apt'

- include_tasks: ppa.yml
  when: ruby_install_type == 'ppa'

- include_tasks: rbenv.yml
  when: ruby_install_type == 'rbenv'

- include_tasks: rvm.yml
  when: ruby_install_type == 'rvm'

- include_tasks: source.yml
  when: ruby_install_type == 'source'

# Install RubyGems
- name: Add user installed RubyGems bin directory to global $PATH
  copy:
    src: rubygems.sh
    dest: /etc/profile.d/rubygems.sh
    mode: 0644

- name: Install Bundler
  gem:
    name: bundler
    state: present
    user_install: no
  when: ruby_install_bundler

- name: Install global Ruby gems
  gem:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    user_install: yes
    executable: "{{ item.executable | default(omit) }}"
  become: yes
  become_user: "{{ ruby_user }}"
  with_items: "{{ ruby_gems }}"

- name : Rehash Rbenv
  shell: "/home/{{ ruby_user }}/.rbenv/bin/rbenv rehash"
  become: true
  become_user: "{{ ruby_user }}"
  when: ruby_install_type == 'rbenv'